"use client";

import AutoGenerateMediaAsset from "@/features/auto-generate-mediaAsset/ui";
import Button from "@/shared/ui/atoms/Button/ui/Button";
import IconButton from "@/shared/ui/atoms/Button/ui/IconButton";
import { ArrowLeft, Sparkles } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";

/**
 * CreateMediaAssetPage 헤더 컴포넌트
 *
 * 책임:
 * - 페이지 제목 표시
 * - 뒤로가기 버튼 제공
 */
export default function MediaAssetCreatePageHeader() {
  const router = useRouter();
  const [openAutoGenerateDialog, setOpenAutoGenerateDialog] = useState<boolean>(false);

  return (
    <header className="flex w-full justify-between py-4 px-2 items-center">
      <h2 className="text-2xl font-bold p-4">Create New Video</h2>
      <div className="flex items-center gap-x-2 ">
        <Button size="sm" onClick={() => setOpenAutoGenerateDialog(true)}>
          <Sparkles size={16} className="mr-2" />
          Auto Generate
        </Button>
        <IconButton onClick={() => router.back()}>
          <ArrowLeft />
        </IconButton>
      </div>
      {openAutoGenerateDialog && (
        <AutoGenerateMediaAsset openDialog={openAutoGenerateDialog} setOpenDialog={setOpenAutoGenerateDialog} />
      )}
    </header>
  );
}
